name: Perm
description: Permission plugin
author: StarTux
version: "0.1"
api: ["1.0.0"]
website: http://cavetale.com
main: com.winthier.perm.PermPlugin
depend: [SQL, GenericEvents]
softdepend: []
commands:
  perm:
    description: Admin command
    permission: perm.perm
    usage: |-
      /perm player <name> ... - Player settings
      /perm group <group> ... - Group settings
      /perm reload - Reload configuration
      /perm refresh - Refresh permission cache
      /perm list <what> ... - List things
permissions:
  perm.perm:
    description: Use /perm
    default: op
