main: com.winthier.perm.PermPlugin
name: Perm

version: 0.1
api-version: 1.19

author: StarTux
description: Permission plugin
website: https://cavetale.com

depend: [Core, SQL, PlayerCache, Mytems]
softdepend: [Vault]

commands:

  perm:
    description: Admin command
    permission: perm.perm
    usage: |-
      /perm player <name> ... - Player settings
      /perm group <group> ... - Group settings
      /perm refresh - Refresh permission cache
      /perm list <what> ... - List things
      /perm level ... - Level commands

  promote:
    description: Promote a player
    permission: perm.promote
    usage: /promote <player> [rank]

  tier:
    description: View tier list
    permission: perm.tier
    usage: /tier

permissions:

  perm.perm:
    description: Use /perm
    default: op

  perm.promote:
    description: Use /promote
    default: op

  perm.tier:
    description: Use /tier
    default: op