main: com.winthier.perm.PermPlugin
name: Perm

version: 0.1
api-version: 1.19

author: StarTux
description: Permission plugin
website: https://cavetale.com

depend: [Core, SQL, PlayerCache]
softdepend: [Vault]

commands:

  perm:
    description: Admin command
    permission: perm.perm
    usage: |-
      /perm player <name> ... - Player settings
      /perm group <group> ... - Group settings
      /perm refresh - Refresh permission cache
      /perm list <what> ... - List things

  promote:
    description: Promote a player
    permission: perm.promote
    usage: /promote <player> [rank]

permissions:

  perm.perm:
    description: Use /perm
    default: op

  perm.promote:
    description: Use /promote
    default: op