name: Perm
description: Permission plugin
author: StarTux
version: 0.1
api-version: 1.17
website: http://cavetale.com
main: com.winthier.perm.PermPlugin
depend: [Core, SQL, PlayerCache]
softdepend: [Vault, Connect]
commands:

  perm:
    description: Admin command
    permission: perm.perm
    usage: |-
      /perm player <name> ... - Player settings
      /perm group <group> ... - Group settings
      /perm reload - Reload configuration
      /perm refresh - Refresh permission cache
      /perm list <what> ... - List things

  promote:
    description: Promote a player
    permission: perm.promote
    usage: /promote <player> [rank]

permissions:

  perm.perm:
    description: Use /perm
    default: op

  perm.promote:
    description: Use /promote
    default: op